import type { FleetVehicle } from "@/components/fleet/fleet-vehicle-card-dark"

export const STANDARD_VEHICLES: FleetVehicle[] = [
  {
    id: "fiat-tipo-station",
    name: "Fiat Tipo Station",
    image: "/fleet/vehicles/fiat-tipo-station.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 4,
    bags: 3,
    hasAc: true,
    hasWifi: true,
  },
  {
    id: "dacia-sandero",
    name: "Dacia Sandero ECO-G 100",
    image: "/fleet/vehicles/dacia-sandero.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 4,
    bags: 3,
    hasAc: true,
    hasWifi: true,
  },
  {
    id: "peugeot-e208",
    name: "Peugeot e-208",
    image: "/fleet/vehicles/peugeot-e208.png",
    badges: ["eco", "electric"],
    paxMin: 1,
    paxMax: 4,
    bags: 3,
    hasAc: true,
    hasWifi: true,
  },
  {
    id: "renault-clio",
    name: "Renault Clio",
    image: "/fleet/vehicles/renault-clio.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 4,
    bags: 3,
    hasAc: true,
    hasWifi: true,
  },
]

export const XL_VEHICLES: FleetVehicle[] = [
  {
    id: "renault-grand-scenic",
    name: "Renault Grand Scenic",
    image: "/fleet/vehicles/renault-grand-scenic.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 3,
    bags: 2,
    hasAc: true,
    hasWifi: true,
  },
  {
    id: "citroen-c4-grand-picasso",
    name: "Citroën C4 Grand Picasso",
    image: "/fleet/vehicles/citroen-c4-grand-picasso.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 3,
    bags: 2,
    hasAc: true,
    hasWifi: true,
  },
  {
    id: "kia-ev6",
    name: "KIA EV6",
    image: "/fleet/vehicles/kia-ev6.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 3,
    bags: 2,
    hasAc: true,
    hasWifi: true,
  },
  {
    id: "kia-niro",
    name: "KIA Niro",
    image: "/fleet/vehicles/kia-niro.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 3,
    bags: 2,
    hasAc: true,
    hasWifi: true,
  },
  {
    id: "dacia-jogger",
    name: "Dacia Jogger",
    image: "/fleet/vehicles/dacia-jogger.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 3,
    bags: 2,
    hasAc: true,
    hasWifi: true,
  },
]

const execBase = (id: string, name: string, image: string, badges: FleetVehicle["badges"]): FleetVehicle => ({
  id,
  name,
  image,
  badges,
  paxMin: 1,
  paxMax: 3,
  bags: 2,
  hasAc: true,
  hasWifi: true,
})

export const EXECUTIVE_VEHICLES: FleetVehicle[] = [
  execBase("mercedes-s400", "Mercedes S400", "/fleet/vehicles/mercedes-s400.png", ["available"]),
  execBase("porsche-panamera", "Porsche Panamera", "/fleet/vehicles/porsche-panamera.png", ["available"]),
  execBase("tesla-model-y", "Tesla Model Y", "/fleet/vehicles/tesla-model-y.png", ["eco", "electric"]),
  execBase("mercedes-eqe", "Mercedes EQE", "/fleet/vehicles/mercedes-eqe.png", ["eco", "electric"]),
  execBase("bentley-flying-spur", "Bentley Flying Spur", "/fleet/vehicles/bentley-flying-spur.png", ["available"]),
  execBase("mercedes-eqs", "Mercedes EQS", "/fleet/vehicles/mercedes-eqs.png", ["eco", "electric"]),
  execBase("mercedes-s-class", "Mercedes S Class", "/fleet/vehicles/mercedes-s-class.png", ["available"]),
  execBase("mercedes-e-class-station", "Mercedes E Class Station", "/fleet/vehicles/mercedes-e-class-station.png", ["available"]),
  execBase("tesla-model-s", "Tesla Model S", "/fleet/vehicles/tesla-model-s.png", ["eco", "electric"]),
]

export const MINIBUS_VEHICLES: FleetVehicle[] = [
  {
    id: "mercedes-sprinter",
    name: "Mercedes Sprinter",
    image: "/fleet/vehicles/mercedes-sprinter.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 16,
    bags: 0,
    hasAc: true,
    hasWifi: true,
    variant: "large",
  },
  {
    id: "ford-transit",
    name: "Ford Transit",
    image: "/fleet/vehicles/ford-transit.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 22,
    bags: 0,
    hasAc: true,
    hasWifi: true,
    variant: "large",
  },
]

export const COACH_VEHICLES: FleetVehicle[] = [
  {
    id: "standard-coach",
    name: "Standard Coach",
    image: "/fleet/vehicles/standard-coach.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 56,
    bags: 0,
    hasAc: true,
    hasWifi: true,
    variant: "large",
  },
  {
    id: "executive-coach",
    name: "Executive Coach",
    image: "/fleet/vehicles/executive-coach.png",
    badges: ["available"],
    paxMin: 1,
    paxMax: 56,
    bags: 0,
    hasAc: true,
    hasWifi: true,
    variant: "large",
  },
]

export const VAN_VEHICLES: FleetVehicle[] = [
  execBase("mercedes-vito", "Mercedes Vito", "/fleet/vehicles/mercedes-vito.png", ["available"]),
  execBase("peugeot-traveller", "Peugeot Traveller", "/fleet/vehicles/peugeot-traveller.png", ["eco", "electric"]),
  execBase("toyota-hiace", "Toyota HiAce", "/fleet/vehicles/toyota-hiace.png", ["available"]),
  execBase("mercedes-v-class", "Mercedes V-Class", "/fleet/van/Mercedes V Class.webp", ["available"]),
  execBase("mercedes-eqv-2025", "Mercedes EQV 2025", "/fleet/van/Van executiva.webp", ["eco", "electric"]),
]
